# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo docker login -u $(DOCKER_USER) -p $(DOCKER_PASSWORD)
  displayName: Login to Docker Hub

- script: sudo docker pull homeassistant/amd64-builder
  displayName: Install hassio builder

- script: |
    docker run --rm --privileged -v ~/.docker:/root/.docker \
    -v /run/docker.sock:/run/docker.sock:rw \
    -v "$(pwd)/Caddy 2":/data \
    homeassistant/amd64-builder --all -t /data \
    --no-cache \
    -d berichta -i caddy-2-{arch} --test
  condition: succeeded()
  displayName: Build and push caddy2 with tag :latest