---
name: Caddy 2
version: dev
slug: caddy-2
description: Open source web and proxy server with automatic HTTPS
url: "https://github.com/einschmidt/addon-caddy-2"
arch:
  - amd64
  - aarch64
startup: services
map:
  - type: share
    read_only: false
  - type: addon_config
    read_only: false
  - type: ssl
    read_only: false
host_network: true
options:
  non_caddyfile_config:
    email: your@email.com
    domain: mydomain.com
    destination: localhost
    port: 8123
  mtls:
    enabled: false
    regenerate_ca: false
    regenerate_server: false
    regenerate_clients: false
    ca:
      country: US
      state: State
      locality: City
      organization: My Organization
      organizational_unit: IT
      common_name: My CA
      email: ca@example.com
    server:
      country: US
      state: State
      locality: City
      organization: My Organization
      organizational_unit: IT
      common_name: mydomain.com
      email: server@example.com
    clients: []
  args: []
  env_vars: []
  log_level: info
schema:
  non_caddyfile_config:
    email: email?
    domain: str?
    destination: str?
    port: port?
  mtls:
    enabled: bool?
    regenerate_ca: bool?
    regenerate_server: bool?
    regenerate_clients: bool?
    ca:
      country: str?
      state: str?
      locality: str?
      organization: str?
      organizational_unit: str?
      common_name: str?
      email: email?
    server:
      country: str?
      state: str?
      locality: str?
      organization: str?
      organizational_unit: str?
      common_name: str?
      email: email?
    clients:
      - name: str
        country: str?
        state: str?
        locality: str?
        organization: str?
        organizational_unit: str?
        common_name: str
        email: email
        p12_password: password?
  caddy_upgrade: bool?
  caddy_fmt: bool?
  args:
    - str
  env_vars:
    - name: str
      value: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
environment:
  LOG_FORMAT: "{LEVEL}: {MESSAGE}"
init: false
breaking_versions:
  - 2.0.0
