# This is a basic workflow to help you get started with Actions

name: 'Test'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
#   build:
#     # Name of the job
#     name: Test build
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
      
#       # Login to DockerHub
#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       # Test build
#       - name: Test build
#         uses: home-assistant/builder@master
#         with:
#           args: |
#             --no-latest \
#             --all \
#             --target "/data/Caddy 2" \
#             --docker-hub ${{ secrets.DOCKERHUB_USERNAME }} \
#             --image caddy-2-{arch} \
#             --version edge
  
  # This workflow updates the dev version number
  update:
    # Name of the job
    name: Update dev version
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: einschmidt/hassio-addons-dev
      - uses: jossef/action-set-json-field@v1
        with:
          file: ./caddy-2/config.json
          field: version
          value: ${{ GITHUB_ACTION }}
